name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Yarn
      run: npm install -g yarn
    - name: run eslint tests
      run: |
        yarn install --frozen-lockfile
        yarn test
      env:
        CI: true
